[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
  "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
